### PR TITLE
Added a docker-compose file

### PR DESCRIPTION
**Pull request by AlexandreL0pes**
The file has been added, if there is another change  please tell me.

### CODE REVIEW

**Comment by Presto412** [comment]
@AlexandreL0pes 

- You can update the dockerfile node version to the latest LTS version
-  Can we add persistence for MongoDB? Let's mount a volume (/tmp would also work)
-  Auth params can be added to the env file
-  Can we use https://hub.docker.com/_/mongo instead of bitnami? Are there any advantages to using bitnami's image over the official one?
-  The URL can also be updated to include the password(I get MongoError: command find requires authentication)

**Comment by AlexandreL0pes** [comment]
Great, I think that

**Comment by AlexandreL0pes** [comment]
Okay! The node version was changed for LTS and a volume was created for mongo data. About the image for mongo, the official will be better for the project. Lastly, I have some issues setting up the password, so I remove the environment variables in mongo, so the URL for connection it's default.

**Comment by Presto412** [comment]
Thanks @AlexandreL0pes !

**Pull request merged**
