### PR TITLE
remaining fixes after removing jquery

### PR DESCRIPTION
**Pull request by chris--jones**
These are fixes to help close off #8 after PR #14 was merged.

- remove remaining jquery $ reference (list.js)
- fix showElement to not enforce display:block (avoid display issues)
- update nav to remove initial-hidden class and remove from style.css

As an aside, I don't think style.css is needed; the only remaining rule is to prevent scrolling which actually makes the site less usable on my laptop and I can't see obvious reasons to do this (unless you really hate scrollbars).

### CODE REVIEW

**Comment by Presto412** [comment]
@chris--jones It lead to a sort of horizontal scrolling that was ugly. Have you tried commenting it out and running the thing? Iirc, it was an issue because of the bulma library. Don't have access to my laptop right now so wouldn't know.

**Comment by chris--jones** [comment]
Yeah it didn't cause me any issues in Firefox, what browser are you using?
If you wanted to stop horizontal scrolling I think that'd be `overflow-x: hidden;` instead.

On an unrelated note I also made some opinionated changes to the list page here: https://github.com/chris--jones/CryptoFS/tree/table-updates, but didn't raise a PR because there's no issue for them
- use table body (tbody)
- add a progress indicator when loading (https://bulma.io/documentation/elements/progress/)
- format the dates (put the existing millisecond value as title)

image

**Comment by Presto412** [comment]
@chris--jones I think I must have left that after the horizontal scrolling issue got fixed. You can delete the style.css and merge the other branch with this PR itself

**Comment by Presto412** [comment]
@chris--jones Just check once if you are able to spot a double scrollbar after deleting the style.css file in either laptop/responsive view, I remember it being an issue in the past.

**Comment by Presto412** [comment]
@chris--jones 
image
This white portion at the side comes up, and that's why I removed the scrollbar

**Comment by Presto412** [comment]
For now I shall merge this PR, and you can submit a separate PR with the changes you've made after this

**Comment by chris--jones** [comment]
> @chris--jones
> image
> This white portion at the side comes up, and that's why I removed the scrollbar

That just looks like the scrollbar :) You'll find a lot of sites actually enforce the display of the scrollbar so that you don't get pages jumping around when navigating, or alternatively use some vendor specific scrollbar css; I'll have a look and see if I can resolve this as well 😉

**Pull request merged**
